Add files for functions
DermaGram/DermaGram pull request #47
Opened 2017-10-30 04:53 UTC by ShoniB

got rid of function definitions inside of app.py and put them into files

2017-10-30 13:53 UTC, DermaGram requested changes

2017-10-30 13:53 UTC, DermaGram commented on master/utils/dologin.py
> +
import logging_utils.
i have some example for how to use in imgur_utils files.

2017-10-30 13:53 UTC, DermaGram commented on master/utils/dologin.py
> +        session['logged_in'] = False
using logging tools, add debug/warn/error statement indicating why we bailed

2017-10-30 13:53 UTC, DermaGram commented on master/utils/dologin.py
> +	session['logged_in'] = False
same here, provide debug/warn/error statement indicating why we bailed.

2017-10-30 13:53 UTC, DermaGram commented on master/utils/dologin.py
> +        flash('wrong password!')
Does 'flash' show popup message for the user? Otherwise, if it's just logging, we can reuse logging_utils.

2017-10-30 13:53 UTC, DermaGram commented on master/utils/doregister.py
> +    if request.method == "POST" and form.validate():
if this condition isn't met, it doesn't look like you return True or False, even though you return a boolean when the condition is met. 

what you can do is create 'status = false' or 'status = 'true' variable at the start of the function, depending on whatever should be the default return value. in your code you can then reset status as needed, depending on the condition statements below. the only return statement you'll have is at the very end of the function 'return status'
 
    status = false  
        if condition:   
            do stuff
            if condition:  
                logger.error(msg)  
            else:  
                status = true  
    return status

2017-10-31 00:42 UTC, jaspalsingh94 submitted a review, later dismissed

2017-10-31 02:45 UTC, ShoniB commented
Changes are in. I also may have accidentally dismissed Jaspal's comment, sorry!

2017-10-31 13:46 UTC, DermaGram approved these changes

2017-10-31 13:46 UTC, merged